### ISSUE TITLE
Creating a new conversation doesn't return to page

### ISSUE THREAD

**Issue by T-Lind** [LindauerAI/client#2]
After writing a message in a new conversation and providing the new conversation name, the UI does not exit out of the text box dialogue and does not add the message in the conversation.
![image](https://github.com/LindauerAI/client/assets/82475207/2379d249-9392-4be8-a43b-565f5986d802)

**Comment by T-Lind** [comment]
This is fixed in the latest version, but a new conversation is created every time a message is sent. This should only happen for the first message sent in a new conversaiton.

**Comment by toptobes** [comment]
Fixed
